# --- Gemini API Key ---
[generativeai]
GOOGLE_API_KEY = "AIzaSyBiiG4SaeN8kdefCneyIsaur1Fon6cZAXo"

# --- Server Configuration ---
[server]
headless = true

# --- Firebase Web Configuration ---
[firebase_web_config]
apiKey = "AIzaSyBo_xudpABy8nwmg226m4PzYZWaT7T7oPM"
authDomain = "resume-4036a.firebaseapp.com"
projectId = "resume-4036a"
storageBucket = "resume-4036a.firebasestorage.app"
messagingSenderId = "647740444740"
appId = "1:647740444740:web:a0418c69b031c2b117ac11"
measurementId = "G-ZQKEXGNBHE"

# --- Firebase Admin SDK Credentials ---
[firebase_credentials]
type = "service_account"
project_id = "resume-4036a"
private_key_id = "1faf9565ff8ee2772c69bf21e28fb245dcb71981"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCUbDXRmiWGrq5o\n+SOD92B2N6BWx8CjMg+ulB24hhVgXoeya4AVlqv1ADSvwsshQmjPZRrijSU6VyiT\nDsQWaSQ1QWkoIM1AEahopBSIGvv2KAHpYhrTwFD01HKajfXE4fInhtcXL7CqcRAA\nJztGFcxawsCVNg70o6Zyn5shLhe2ssd1RYT/84vck3bHFhobVjYBAN8w267aQQsL\ntAjKezfhTo2ac3xmlFrTJ4tLLnXowDIVzJaBaydFqtZD2qoc0CjrX5vOmPYQo2vy\nHibPwE8FgBcW7DiSo9GqVA1spsebBOP3Qf3fAZD7u7RNRxY/75cXOJPyjWUj2u03\nMZts36WLAgMBAAECggEAFJ3pZemrH8fA+1zsJYcl05YLhDJwHFs2WXJCpKCfdIj9\nAXg0TQtmbHxwVR/SVpbidzicoO6pRq7XuIG7FD/bozgoUsYnrKgnRA3SuktBR6Ks\nDU6u2k4jELc4CicBBi26lOoCk7pwqGRXLCZG8gfSIKNf2/or3qii1NY91sCP07VQ\nniqozittEjSU119uaPnccirgHLAZOAmA4KZjrDFjysSie/ZFWqWbOb+NP3piipsg\nSCe6tU6YxMwSspH8R+Es2PIlv74N8FDNpp72pYDCa2jFP/3tzLVwgZHbUYusCW5d\nG9TgA1LjFA+JKxQoeZZCfeJS2NSYuyFAtKWfnEr84QKBgQDFRpljSuXjdrCDrKjj\npBZwzLXzCBt9NwhARhyjMuTtDIPxmU9Wy5yzRdhwnRSrGZAXSfdkgYV+DGVZ2oeh\nmuZTJ7ilmC83j2p+0QLTwa5NU0hr8ijzZZBmks+zATKomyMiPRCs0/qv5LozrV/d\ne6szyuFaSpG9ZEbtXLBHzk2KoQKBgQDAmsMNFdNQXID9FmXLfvXw0bgmnv5trBZ5\nBQZlR85PU34u7yon6eBNtZWo+MXAfTlxqxXkQgd9EAW1JED/bZx7TzsursbVdIhw\ng1SSRaPjAufM3g+5IR4gXCLf7VvrrPvaGk+URmEQ9A/vqEnFPQ31FndKcKumLmdV\ncVnvlMSMqwKBgA4bBDCzVEi1Xd2sZM8SFoCuQnxEIiML4k0mNjn9E51Xfb+ypJei\nK2wuHFHBCY9KXqErqsLG+BKRNFX+aCBIARwFBRDiFs40NPsoWrllad8hi1YclI0C\nwBZ1fOBhv4uKvDJgh2a0KYKWKjIzvV0K0Kz9XqukFVOjbebe78PSnnzBAoGAeOVs\nA52si6fU64gQk4B4/hWWAuAQEmVPod0um4pMDOz6qplDG9SpD/4oF+03q9CuqxPZ\n5PIxYyYYfxBnoC18aMZd/rqEYl4Iep9lCX+fFJKxT54fvnP0RhmvZmHGLhPh7pBP\nXWIj8ZFRI3y9+YmOZkYY0OgSRnigMji5XDJEgYsCgYBZJ7dgn623rdXF6AtYFIUf\nOzLnlNwxKN1w0VFwoGcea8p3YIzmuPvPoRytZ79kRmQPag7poWo6AB3ZyTobEsSv\n0hXdfjyxRz8hFiRjdJjHwcDSSGK4ar3BcQEDiacyvmhQ7vQi4rIPHY2g6UEK9KMB\nWa8slydAECGPqs5sgslaWg==\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@resume-4036a.iam.gserviceaccount.com"
client_id = "117261812336885346646"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40resume-4036a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

