# --- Gemini API Key ---
[generativeai]
GOOGLE_API_KEY = "AIzaSyBiiG4SaeN8kdefCneyIsaur1Fon6cZAXo"

# --- Server Configuration ---
[server]
headless = true

# --- Firebase Admin SDK Credentials ---
# These should be copied directly from your Firebase service account JSON key file.
[firebase_credentials]
type = "service_account"
project_id = "resumely-d8fac"
private_key_id = "0b72ad67b908e4e8d07a957059096310a1f76202"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVwPdWYzbTsZAv\noeUiNCv2MuYOaG+epRzDk63I9nMEtT+fZTz6a52G39TytW30FNQhEjkPWmLVLebY\nTxNWyi27XDFVAtPyGqDZs3YF457ORAS3p3Uh/WMTku7aavPnkN2IggI37yK4bJof\n7PYkkT8eMu+GFkQRE5FlW42P7S3dV+Y5JHRGAQU7obmOzBl4Hdm78wVDGQtz3iIy\nuysjeg+4eHXppvbr5ltTRPg+B1d9GNfwSz2fKkgCT9c0bGkYRQLLy5Em4ql/Z9rv\n/5YhxkeMwP149jiiQ4CnAwURiDDz678XX1uI/e66y/+v574kfbqQq0rhjr2/e7od\nCK7xRQwLAgMBAAECggEAP8cBz4nLhNbfaFnTowCDJIRC1CoIN5FsMaMIZUkIbR3f\n7buI/8GrQhC7uW4pWMUyHq+LG43L/6xf3wm2W8UZOu0lmWXt6/MJRA4ZGqL5NDFl\nrO2lhgdLFcAC94SLQbjBkGyGE1pF+DNQZH5fye0N64eX2QxMitVBm+Ak5wIFAXnR\n64EiztSLM7nz8nU4BM88JA8EsuwXX7wVUihVaE5/A7B/fGZGWfjdfSI8fpMUGtzb\n35KXDSZhlHu7ZshGfet9ivMfIa3oLXbKL8QFc01JZzPy3DVzeH75jswLJacZQlie\nX9Afamc1J2SvKjAvtKa0fsbU87+UaTFrRZNf6+NkAQKBgQDO9FlbHvw164gGoSis\nRdV0m8NqIFBFF2NdVrhZXmIEgqRQmA7f3CcjuL9gli9dXEWytKp1kuAN5cCxFyC+\nPIcW2oW80lvjUdumos8j7Rnb88GRIfssBNxRhwxB6U+9pBNKIiY/j3O1uJHdLXLK\nX4p/Nni6HXu0p5q8s1MfTDpqCwKBgQC5PlOaOKToL1Ynl61BK6YrjOHK+kX/Yp7g\n8SDOhGLia66aZn/SvwD1PCT1okCtssnbSxstG4xXYXTakaxKwuwuWAL0nhOTMkyQ\nG7aofe7Kq5O3N/ec2rkZTC0560ngyPHY+YeEyaWrXnZaZVUd/VX8TKzLUJD77vuA\nfXzBGQcmAQKBgA8hD9M4famXcVdCus11QXiH1o5QlG2omwv8xfdKjhHUVxzJMPUu\ni/HxlJQEBqxljXbV/EwiE50Qebi4fx1JIXsLOJGoMy14E32oE0qGD8jjlff9KvZ5\n2H1hSQUcgEbV0s8tlew5mXTkbE1mAClJOL+6BLNeame3hPlchqwYD4EnAoGAOAww\nlWfwFURFSANva1l+lIyywIxK44N+WMb8Sx/pH2K/WH4MzMH30ztYX22xLhz7UDuA\nRHyiUMnu5jbPL2uctETy1/qAJ7g/TBbmhEJeHrodHoFzjOTsvke7I1waZUXHTwPo\nyfeNBbW2D5G7WDCPdJ/qZDXDOEbNl8ngFjixXgECgYEAopZTtiBaafDZuLNTFpbb\nTXai67nLFNlXYXN4xPdRi4WTTxhTYad7y+HfwTM/ny5Cs3vH4BDzwRK9oxkR6+zH\n1epPBDYkiO/0aRPMhJys5ZC10EfdENlenkEzMXb11Gq4E6fGF3zmBF5ESMGERclS\ncFNPokNOgXbwCi/eDgbLQmU=\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk-fbsvc@resumely-d8fac.iam.gserviceaccount.com"
client_id = "115710318753169548256"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40resumely-d8fac.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

