# --- Gemini API Key ---
[generativeai]
GOOGLE_API_KEY = "AIzaSyBiiG4SaeN8kdefCneyIsaur1Fon6cZAXo"

# --- Server Configuration ---
[server]
headless = true

# --- Firebase Web Configuration ---
[firebase_web_config]
apiKey = "AIzaSyBo_xudpABy8nwmg226m4PzYZWaT7T7oPM"
authDomain = "resume-4036a.firebaseapp.com"
projectId = "resume-4036a"
storageBucket = "resume-4036a.firebasestorage.app"
messagingSenderId = "647740444740"
appId = "1:647740444740:web:a0418c69b031c2b117ac11"
measurementId = "G-ZQKEXGNBHE"

# --- Firebase Admin SDK Credentials ---
# You'll need to generate service account key from Firebase Console > Project Settings > Service Accounts
[firebase_credentials]
type = "service_account"
project_id = "resume-4036a"
private_key_id = "your_private_key_id"
private_key = "-----BEGIN PRIVATE KEY-----\nyour_private_key_here\n-----END PRIVATE KEY-----"
client_email = "your_service_account_email@resume-4036a.iam.gserviceaccount.com"
client_id = "your_client_id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your_service_account_email%40resume-4036a.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

